# DS222_Assignment2
Logistic regression classifier implementation for DBPedia dataset with 50 classes

** Installation
Simply clone this repository via

#+BEGIN_SRC sh
  git clone https://github.com/sobalgi/DS222_assignment2.git
#+END_SRC

** Dependencies
- Python with NumPy
- h5py

This consists of 2 parts each included in separate folders.

#+BEGIN_SRC sh
  cd part1_logreg_local
  ./train_n_log_accuracies.sh
#+END_SRC
To reproduce or run the In-Memory local implementation of logistic regression and generate logs.


'part1_logreg_local' folder has the code files and generated log files for In-Memory local implementation of logistic regression with L2 regularization.

Also the execution times for training only, training accuracy, development accuracy and testing accuracy are logged individually for better comparisions.

#+BEGIN_SRC sh
  cd part2_logreg_ps
  ./training.sh # for training model parameters in ASP, BSP and SSP configurations.

#+END_SRC

'part2_logreg_ps' folder has the codes for ASP, BSP and SSP SGD implementation of L2 regularized logistic regression and appropriate logs.

The detailed report is also included as 'DS222_as2_report.pdf'

  
